language: perl
perl:
  - 5.18
  - 5.16
  - 5.14
  - 5.12
before_install:
  - perlbrew install-cpanm -f
install:
  - (cpanm --installdeps --with-develop -nq .) || cat ~/.cpanm/build.log
script:
  - prove -lr xt t
